#!/usr/bin/env bash
set -euo pipefail

target="THIRD_PARTY_LICENSES.md"
check=false
if [[ "${1:-}" == "--check" ]]; then
	check=true
elif [[ "${1:-}" != "" ]]; then
	target="$1"
fi

modcache="${GOMODCACHE:-$(go env GOMODCACHE)}"
fallback_modcache="$(env -u GOMODCACHE go env GOMODCACHE 2>/dev/null || true)"
modules_file="$(mktemp)"
generated_file="$(mktemp)"
trap 'rm -f "$modules_file" "$generated_file"' EXIT

awk '
	$1 == "require" && $2 == "(" { in_require = 1; next }
	$1 == ")" { in_require = 0; next }
	$1 == "require" && NF >= 3 { print $2 "\t" $3; next }
	in_require && NF >= 2 && $1 !~ /^\/\// { print $1 "\t" $2 }
' go.mod | sort -u > "$modules_file"

module_dir_in_cache() {
	local module="$1"
	local version="$2"
	local cache="$3"
	if [[ "$cache" == "" ]]; then
		return 1
	fi
	local direct="${cache}/${module}@${version}"
	if [[ -d "$direct" ]]; then
		printf '%s\n' "$direct"
		return 0
	fi
	find "$cache" -type d -path "*/${module}@${version}" -print -quit 2>/dev/null || true
}

module_dir() {
	local module="$1"
	local version="$2"
	local found
	found="$(module_dir_in_cache "$module" "$version" "$modcache")"
	if [[ "$found" != "" ]]; then
		printf '%s\n' "$found"
		return 0
	fi
	local downloaded
	downloaded="$(GOMODCACHE="$modcache" go mod download -json "${module}@${version}" 2>/dev/null | awk -F '"' '$2 == "Dir" { print $4; exit }' || true)"
	if [[ "$downloaded" != "" && -d "$downloaded" ]]; then
		printf '%s\n' "$downloaded"
		return 0
	fi
	if [[ "$fallback_modcache" != "$modcache" ]]; then
		module_dir_in_cache "$module" "$version" "$fallback_modcache"
	fi
}

license_source() {
	local module="$1"
	local version="$2"
	local dir="$3"
	for candidate in LICENSE LICENSE.txt LICENSE.md COPYING; do
		if [[ -f "${dir}/${candidate}" ]]; then
			printf '%s\t%s@%s/%s\n' "${dir}/${candidate}" "$module" "$version" "$candidate"
			return 0
		fi
	done

	if [[ "$module" == "github.com/mattn/go-localereader" ]]; then
		local go_isatty_version
		go_isatty_version="$(awk -F '\t' '$1 == "github.com/mattn/go-isatty" { print $2 }' "$modules_file")"
		if [[ "$go_isatty_version" != "" ]]; then
			local go_isatty_dir
			go_isatty_dir="$(module_dir "github.com/mattn/go-isatty" "$go_isatty_version")"
			if [[ -f "${go_isatty_dir}/LICENSE" ]]; then
				printf '%s\tgithub.com/mattn/go-isatty@%s/LICENSE\n' "${go_isatty_dir}/LICENSE" "$go_isatty_version"
				return 0
			fi
		fi
	fi

	return 1
}

notice_source() {
	local dir="$1"
	local module="$2"
	local version="$3"
	if [[ -f "${dir}/NOTICE" ]]; then
		printf '%s\t%s@%s/NOTICE\n' "${dir}/NOTICE" "$module" "$version"
	fi
}

write_license_block() {
	local module="$1"
	local version="$2"
	local dir="$3"
	local source="$4"
	local source_label="$5"
	local notice="$6"
	local notice_label="$7"

	printf '### %s %s\n\n' "$module" "$version"
	if [[ "$module" == "github.com/mattn/go-localereader" ]]; then
		printf 'Upstream does not ship a standalone license file. Its README declares MIT; this project uses the MIT text from github.com/mattn/go-isatty, matching go-vendor-tools.toml.\n\n'
	fi
	printf 'Source: `%s`\n\n' "$source_label"
	printf '```text\n'
	sed 's/[[:space:]]*$//' "$source"
	printf '\n```\n\n'

	if [[ "$notice" != "" ]]; then
		printf 'Notice: `%s`\n\n' "$notice_label"
		printf '```text\n'
		sed 's/[[:space:]]*$//' "$notice"
		printf '\n```\n\n'
	fi
}

missing=0
{
	printf '# Third-Party Licenses\n\n'
	printf 'Generated by `scripts/generate-third-party-licenses.sh` from `go.mod`.\n'
	printf 'The project license is in `LICENSE`.\n\n'
	printf '## Module Summary\n\n'
	printf '| Module | Version | Notice source |\n'
	printf '| --- | --- | --- |\n'

	while IFS=$'\t' read -r module version; do
		dir="$(module_dir "$module" "$version")"
		if [[ "$dir" == "" ]]; then
			printf 'Missing module cache entry for %s %s\n' "$module" "$version" >&2
			missing=1
			continue
		fi
		if ! source_record="$(license_source "$module" "$version" "$dir")"; then
			printf 'Missing license source for %s %s in %s\n' "$module" "$version" "$dir" >&2
			missing=1
			continue
		fi
		source="${source_record%%$'\t'*}"
		source_label="${source_record#*$'\t'}"
		notice_record="$(notice_source "$dir" "$module" "$version")"
		notice=""
		notice_label=""
		summary_source="$source_label"
		if [[ "$notice_record" != "" ]]; then
			notice="${notice_record%%$'\t'*}"
			notice_label="${notice_record#*$'\t'}"
			summary_source="${summary_source}; ${notice_label}"
		fi
		printf '| `%s` | `%s` | `%s` |\n' "$module" "$version" "$summary_source"
	done < "$modules_file"

	printf '\n## License Texts\n\n'
	while IFS=$'\t' read -r module version; do
		dir="$(module_dir "$module" "$version")"
		if [[ "$dir" == "" ]]; then
			continue
		fi
		if ! source_record="$(license_source "$module" "$version" "$dir")"; then
			continue
		fi
		source="${source_record%%$'\t'*}"
		source_label="${source_record#*$'\t'}"
		notice_record="$(notice_source "$dir" "$module" "$version")"
		notice=""
		notice_label=""
		if [[ "$notice_record" != "" ]]; then
			notice="${notice_record%%$'\t'*}"
			notice_label="${notice_record#*$'\t'}"
		fi
		write_license_block "$module" "$version" "$dir" "$source" "$source_label" "$notice" "$notice_label"
	done < "$modules_file"
} > "$generated_file"

if [[ "$missing" -ne 0 ]]; then
	exit 1
fi

if [[ "$check" == true ]]; then
	diff -u "$target" "$generated_file"
else
	chmod 0644 "$generated_file"
	mv "$generated_file" "$target"
fi
